name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]  # Il dépend du succès du pipeline CI
    types:
      - completed

permissions:
  contents: read
  packages: write
  id-token: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  TAG_NAME: 0.1
  COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}

jobs:
  sign_and_verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Sign the Docker image with Cosign
        uses: sigstore/cosign-action@v1
        with:
          cosign-version: 'v1.8.0'  # Choisissez la version souhaitée
          sign: true
          image: ghcr.io/${{ github.repository }}:${{ github.sha }}
          key: ${{ secrets.COSIGN_PRIVATE_KEY }}
          password: ${{ secrets.COSIGN_PASSWORD }}

      - name: Verify the Docker image signature
        uses: sigstore/cosign-action@v1
        with:
          cosign-version: 'v1.8.0'  # Choisissez la version souhaitée
          verify: true
          image: ghcr.io/${{ github.repository }}:${{ github.sha }}
          key: ${{ secrets.COSIGN_PUBLIC_KEY }}
