name: Security and Deploy

on:
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed

jobs:
  security_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Docker image
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Load Docker image
        run: |
          docker load < image.tar.gz

      - name: Install Trivy
        run: |
          sudo apt update
          sudo apt install -y wget
          wget https://github.com/aquasecurity/trivy/releases/download/v0.59.1/trivy_0.59.1_Linux-64bit.tar.gz
          tar -xvzf trivy_0.59.1_Linux-64bit.tar.gz
          sudo mv trivy /usr/local/bin/
      - name: Scan for vulnerabilities with Trivy
        run: trivy fs --exit-code 1 --severity CRITICAL,HIGH .

      - name: Install Snyk
        run: npm install -g snyk

      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Scan dependencies with Snyk
        run: snyk test --severity-threshold=high

  deploy:
    runs-on: ubuntu-latest
    needs: security_scan
    steps:
      - name: Download Docker image
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Load Docker image
        run: |
          docker load < image.tar.gz

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}:${{ github.sha }}

      - name: Install Cosign
        run: |
          curl -LO https://github.com/sigstore/cosign/releases/latest/download/cosign-linux-amd64
          chmod +x cosign-linux-amd64
          sudo mv cosign-linux-amd64 /usr/local/bin/cosign
      - name: Sign Docker image
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        run: |
          cosign sign --yes --key cosign.key ghcr.io/${{ github.repository }}:${{ github.sha }}

      - name: Verify Docker image signature
        run: |
          cosign verify --key cosign.pub ghcr.io/${{ github.repository }}:${{ github.sha }}
